<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://jasmine.com/GetHumidity/" xmlns:humidity="http://jasmine.com/Humidity" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetHumidity" targetNamespace="http://jasmine.com/GetHumidity/">
  <wsdl:import location="../xsd/Humidity.xsd" namespace="http://jasmine.com/Humidity"/>
  
  <wsdl:message name="getHumidityRequest">
    <wsdl:part element="humidity:getHumidity" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="getHumidityResponse">
    <wsdl:part element="humidity:getHumidityResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="GetHumidity">
    <wsdl:operation name="getHumidity">
      <wsdl:input message="tns:getHumidityRequest"/>
      <wsdl:output message="tns:getHumidityResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GetHumiditySOAP" type="tns:GetHumidity">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getHumidity">
      <soap:operation soapAction="http://jasmine.com/GetHumidity/getHumidity"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetHumidity">
    <wsdl:port binding="tns:GetHumiditySOAP" name="GetHumiditySOAP">
      <soap:address location="http://jasmine.com/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>